apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::389816354221:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-QGX60IEZAL3W
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
    - system:masters
    rolearn: arn:aws:iam::389816354221:role/UdacityFlaskDeployCBKubectlRole
    username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-13T15:14:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1675"
  uid: c72e1972-7d4b-4aa8-8f1f-3e7726811a5a
