apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::389816354221:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-14ZMDFXVZ1UXX
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::389816354221:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-09T12:34:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "5471"
  uid: 53f0e997-8b70-4880-af96-91ca499e14fb
